services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./appsettings.Development.json:/app/appsettings.Development.json:ro

  sqlserver:
    ports:
      - "1433:1433"
